#!/bin/bash


qmid=$(get-avail-qm-id)

if [[ $1 -eq "deb" ]]; then
  qm clone 100 $qmid --name "deb-clone-$qmid"
  elif [[ $1 -eq "manj" ]]; then
  qm clone 101 $qmid --name "deb-clone-$qmid"
else
  echo "not valid"
  exit 1
fi
