---
- name: Install nginx deps
  apt:
    pkg:
      - "nginx"
      - "python3-certbot"
      - "cron"
      - "python3-certbot-nginx"

- name: Allow connections on http and https
  iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT

- name: "place nginx conf"
  template:
    src: "../../../assets/nginx/nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/default"
    mode: 0644

- name: "place .env conf"
  template:
    src: "../../../assets/nginx/.env.j2"
    dest: "/infra/assets/nginx/.env"
    mode: 0644

- name: Start and enable service
  service:
    name: nginx
    state: restarted
    enabled: true

# actually doing this as part of the play has a danger of causing
# us to get rate limited while testing
- name: remind to run initial cert
  debug:
    msg: "ssh into vm and run init-certbot on first run"
