---
- name: Install samba
  command:
    argv:
      - yay
      - "-S"
      - "--noconfirm"
      - "samba"
      - "manjaro-settings-samba"
    creates: "/usr/bin/samba"
- name: "as super user"
  block:
    - name: copy samba config over
      copy:
        src: ./smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0700'

    - name: Start and enable service samba
      service:
        name: smb
        state: started
        enabled: true
  become: true
