---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install package base-apts from repo
  apt:
    pkg:
      - neovim
      - htop
      - tmux
    state: latest
    update_cache: yes

