---
- name: Install restic
  apt:
    pkg:
      - "restic"

# cron this
# restic backup --verbose $BACKUP_EXCLUDES $BACKUP_PATHS
#
#
export BACKUP_PATHS="$HOME/personal $HOME/code"
export BACKUP_EXCLUDES="--exclude-file=$HOME/.restic_excludes"

- name: "restic backup daily"
  cron:
    name: "restic backup"
    minute: "0"
    hour: "*/12"
    job: "restic backup --verbose $BACKUP_EXCLUDES $BACKUP_PATHS"


- name: Install snapraid
  apt:
    pkg:
      - "snapraid"

- name: copy snapraid config over
  copy:
    src: ./snapraid.conf
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: '0644'

- name: "snapraid sync and scrub every 3 hours"
  vars:
    job: "snapraid sync; snapraid scrub"
    cadence: "0 */3 * * *"
    dest: "/etc/cron.d/snapraid-sync-scrub"
  include_role:
    name: "../../roles/common/has-cron-job"
