---
- name: Install restic
  apt:
    pkg:
      - "restic"

- name: "copy over env script"
  template:
    src: "../../../assets/restic/.env.j2"
    dest: "/infra/assets/restic/.env"
    mode: 0700
    force: true

- name: "clear restic_backup crontabs"
  shell: "crontab -l | sed /restic_backup/d | crontab -"
  args:
    executable: /bin/bash

- name: "restic daily backeup"
  vars:
    job: >
      /mnt/storage/infra/nas/restic/restic_backup
    cadence: "@daily"
    dest: "/etc/cron.d/restic-backup-daily"
  include_role:
    name: "../../roles/common/has-cron-job"

