---
- name: "Download headscale installer"
  get_url:
    url:  "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_amd64.deb"
    dest: "/headscale.deb"
    mode: 0644

- name: "Install headscale.deb package"
  apt:
    deb: "/headscale.deb"

- name: "Remove the headscale installed"
  file:
    path: "/headscale.deb"
    state: absent

- name: Copy config file
  copy:
    src: ./config.yaml
    dest: /etc/headscale/config.yaml
    owner: root
    group: root
    mode: '0644'
    force: yes

- name: "Run headscale users create infra"
  command:
    cmd: "/usr/bin/headscale users create main"
  ignore_errors: yes

- name: "Allow all access to tcp port 8080"
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: "Start and enable headscale service"
  systemd:
    name: headscale
    state: started
    enabled: yes

