---
- name: "Add parity {{item.number}} to fstab"
  lineinfile:
    dest: /etc/fstab
    regexp: "^/dev/disk/by-id/{{ item.id }}"
    line: "/dev/disk/by-id/{{ item.id }} /mnt/parity{{ item.number }}   ext4 defaults 0 0"
    state: present

- name: "add mount point for {{ item.number }}"
  file:
    state: directory
    path: "/mnt/parity{{ item.number }}"
    mode: '0777'

- name: Add content snapraid conf
  lineinfile:
    dest: /etc/snapraid.conf
    regexp: "^content /mnt/parity{{ item.number }}/.snapraid.content"
    line: "content /mnt/parity{{ item.number }}/.snapraid.content"
    state: present

- name: Add parity {{ item.number }} to snapraid conf
  lineinfile:
    dest: /etc/snapraid.conf
    regexp: "^{{ item.number }}-parity /mnt/parity{{ item.number }}/snapraid.parity"
    line: "{{ item.number }}-parity /mnt/parity{{ item.number }}/snapraid.parity"
    state: present
