---
- name: Install snapraid
  apt:
    pkg:
      - "snapraid"

- name: copy snapraid config over
  copy:
    src: ./snapraid.conf
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: '0644'

- name: "snapraid sync and scrub every 3 hours"
  vars:
    job: "snapraid sync; snapraid scrub"
    cadence: "0 */3 * * *"
    dest: "/etc/cron.d/snapraid-sync-scrub"
  include_role:
    name: "../../roles/has-cron-job"
