---
- name: Install snapraid
  apt:
    pkg:
      - "snapraid"

- name: copy snapraid config over
  copy:
    src: ./snapraid.conf
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: '0644'

- name: "snapraid sync and scrub every 3 hours"
  cron:
    name: "snapraid-sync"
    minute: "0"
    hour: "*/3"
    job: "snapraid sync; snapraid scrub"
