---
- name: Remove paid update list
  lineinfile:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
    line: "#deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
    state: present

# https://pve.proxmox.com/wiki/Package_Repositories#sysadmin_no_subscription_repo
- name: copy custom list from wiki
  copy:
    src: ./sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: "no-nag-script"
  command:
    cmd: echo "DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/data.status/{s/\!//;s/Active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };" > /etc/apt/apt.conf.d/no-nag-script

- name: "reinstall widget"
  command:
    cmd: apt --reinstall install proxmox-widget-toolkit

- synchronize:
    src: ./scripts/
    dest: /usr/bin/

# - name: copy storage.cfg over
#   copy:
#     src: ./storage.cfg
#     dest: /etc/pve/storage.cfg
#     owner: root
#     group: root
#     mode: '0644'
