---
- name: pull down latest infra
  git:
    repo: 'https://github.com/HoffsMH/infra.git'
    dest: "/infra"
    force: yes
    version: master

- name: check if rules file exists
  stat:
    path: /infra/deployables/{{ service_name }}/Dockerfile
  register: dockerfile_present

- name: build docker
  command:
    cmd: "docker build /infra/deployables/{{ service_name }} -t {{ service_name }}"
  when: dockerfile_present.stat.exists
  retries: 5
  delay: 5

- name: "convert .env template"
  template:
    src: "../../../deployables/{{ service_name }}/.env.j2"
    dest: "/infra/deployables/{{ service_name }}/.env"
    mode: 0644

- name: "place service file"
  copy:
    remote_src: true
    src: "/infra/deployables/{{ service_name }}/service"
    dest: "/etc/systemd/system/docker-{{ service_name }}.service"
    mode: 0644
    force: true

- name: reload systemctl after putting in new service file
  command:
    cmd: "systemctl daemon-reload"

- name: reset failed
  command:
    cmd: "systemctl reset-failed"

- name: Start and enable service
  service:
    name: docker-{{ service_name }}
    state: started
    enabled: true

- name: check if afterbuild file exists
  stat:
    path: /infra/deployables/{{ service_name }}/afterbuild
  register: afterbuild_present

- name: Sleep for 300 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 100
  delegate_to: localhost

- name: execute afterbuild
  command:
    cmd: "/infra/deployables/{{ service_name }}/afterbuild"
  when: afterbuild_present.stat.exists
