---
- name: Update all packages to their latest version
  apt:
    upgrade: full
    update_cache: yes

- name: Install package base-apts from repo
  apt:
    pkg:
      - neovim
      - htop
      - tmux
      - jq
    state: latest
    update_cache: yes

