version: '3'
services:
  syncthing:
    container_name: jellyfin
    hostname: 'deb-1-jellyfin'
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - /mnt/storage/data:/data
      - /mnt/storage/infra/.config/syncthing:/var/syncthing
    restart: unless-stopped
    tty: true
    stdin_open: true
networks:
  default:
