---
- name: "Add disk {{ item.number }} to fstab"
  lineinfile:
    dest: /etc/fstab
    regexp: "^/dev/disk/by-id/{{ item.id }}"
    line: "/dev/disk/by-id/{{ item.id }} /mnt/app-data-disk{{ item.number }}   ext4 defaults 0 0"
    state: present

- name: "add mount point for {{ item.number }}"
  file:
    state: directory
    path: "/mnt/app-data-disk{{ item.number }}"
    mode: '0777'
