---
- name: "as super user"
  block:
    - name: Install package syncthing from repo
      pacman:
        name:
          - syncthing
        state: present

    - name: Start and enable service syncthing
      service:
        name: "syncthing@{{ ansible_user }}"
        state: started
        enabled: true

    - name: stop service syncthing
      service:
        name: "syncthing@{{ ansible_user }}"
        state: stopped

    - name: replace listen addr
      lineinfile:
          dest: /home/deploy/.config/syncthing/config.xml
          regexp: "<listenAddress>default</listenAddress>"
          line: "<listenAddress>0.0.0.0</listenAddress>"
          state: present

    - name: replace gui addr
      lineinfile:
          dest: /home/deploy/.config/syncthing/config.xml
          regexp: "<address>127.0.0.1:8384</address>"
          line: "<address>0.0.0.0:8384</address>"
          state: present

    - name: Start and enable service syncthing
      service:
        name: "syncthing@{{ ansible_user }}"
        state: started
        enabled: true
  become: true
