---
- hosts: deb-1
  vars:
    hostname: "{{device_name}}.media-center"
    ansible_host_key_checking: false
  roles:
    - role: ../../roles/infra/service
      service_name: syncthing
    # - ../../roles/nas/syncthing
    # - ../../roles/nas/restic
