---
- hosts: mhkr.xyz
  vars:
    ansible_host_key_checking: false
    ansible_user: root
  roles:
    - ../../roles/infra/repo
    - ../../roles/vm-nginx
    - ../../roles/headscale
    - ../../roles/static-site
