---
- hosts: closet
  vars:
    ansible_host_key_checking: false
    hostname: "closet"
  roles:
    - ../../roles/common/yubi-ssh-secured
    - ../../roles/common/hostname
    - ../../roles/debian/base-apt
    - ../../roles/debian/docker-ce
    - ../../roles/infra/repo
    - ../../roles/debian/tailscale
    - ../../roles/nas/snapraid
    - ../../roles/nas/data-disks
    - ../../roles/nas/parity-disks
    - ../../roles/nas/mergerfs-storage
    - ../../roles/nas/samba-server
    - ../../roles/nas/immich-server
    - ../../roles/nas/atuin-server
    - ../../roles/nas/jellyfin-server
    - ../../roles/nas/syncthing-server/
    # 
