---
- hosts: thinkcentre-a
  vars:
    hostname: "{{device_name}}-proxmox-nas"
    ansible_host_key_checking: false
  roles:
    - ../../roles/common/hostname
    - ../../roles/debian/base-apt
    - ../../roles/infra/repo
    - ../../roles/nas/mergerfs-storage
    - ../../roles/nas/snapraid
    - ../../roles/nas/data-disks
    - ../../roles/nas/parity-disks
    - ../../roles/nas/samba-server
    - ../../roles/nas/restic
