---
- hosts: rpi3-a
  vars:
    ansible_host_key_checking: false
    hostname: "{{device_name}}.pihole"
  roles:
    - ../../roles/common/hostname
    - ../../roles/debian/base-apt
    - ../../roles/debian/docker-ce
    - ../../roles/pi-hole
    - role: ../../roles/infra/service
      service_name: pi-hole-1
