---
- hosts: thinkcentre-a
  vars:
    ansible_host_key_checking: false
  roles:
    - ../../roles/proxmox
    - ../../roles/debian/base-apt
    - ../../roles/infra/repo

  handlers:
    - name: reboot
      reboot:
        reboot_timeout: 36000
