---
- hosts: empty
  vars:
    ansible_host_key_checking: false
    ansible_user: root
    samba_server: "{{ hostvars['thinkcentre-a']['ansible_host'] }}"
  roles:
    - ../../roles/debian/base-apt
    - ../../roles/debian/docker-ce
    - ../../roles/common/samba-client
    - role: ../../roles/infra/service
      service_name: syncthing
