---
- hosts: thinkcentre-a
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: get qmid
      command:
        cmd: "get-avail-qm-id"
      register: qmid

    - name: get qmid
      command:
        cmd: "get-avail-qm-id"
      register: qmid

    - name: clone
      command:
        cmd: "qm clone 100 {{ qmid.stdout }} --description=test-deb --name=test-deb-{{ qmid.stdout }}"

    - name: start
      command:
        cmd: "qm start {{ qmid.stdout }}"

    - name: "get ip of newly started vm"
      command:
        cmd: "get-ip-address {{ qmid.stdout }}"
      register: qmip
      until: qmip.stdout != ""
      retries: 10
      delay: 10

    - name:
      debug:
        msg: "{{ qmip }}"

    # - name: "example test play"
    #   vars:
    #     ansible_host: "{{ qmip.stdout }}"
    #     repo_url: https://github.com/HoffsMH/mhkr.io
    #     cert_email: "example@example.com"
    #     domain: "example.com"
    #     www_domain: "www.example.com"
    #     static_files_dir: public
    #   include_role:
    #     name: "../../roles/static-site"

    # - name: "stop vm"
    #   command:
    #     cmd: "qm stop {{ qmid.stdout }}"
    #   retries: 10
    #   delay: 10
    #
    # - name: "destroy vm"
    #   command:
    #     cmd: "qm destroy {{ qmid.stdout }}"
    #   retries: 10
    #   delay: 10

