---
- name: "clear old backup crons to make this idempotent"
  shell: "crontab -l | sed /backup.dir/d | crontab -"
  args:
    executable: /bin/bash

- name: "weekly personal backup"
  vars:
    job: "sudo /home/hoffs/bin/backup.dir workstation hoffs /home/hoffs/personal weekly 2"
    cadence: "@weekly"
    dest: "/etc/cron.d/hoffs-workstation-backup"
  include_role:
    name: ../../roles/common/has-cron-job

- name: "daily jrnl backup"
  vars:
    job: "sudo /home/hoffs/bin/backup.dir workstation hoffs /home/hoffs/personal/jrnl daily 5"
    cadence: "@daily"
    dest: "/etc/cron.d/hoffs-workstation-backup"
  include_role:
    name: ../../roles/common/has-cron-job

- name: "monthly personal backup"
  vars:
    job: "sudo /home/hoffs/bin/backup.dir workstation hoffs /home/hoffs/personal monthly 4"
    cadence: "@monthly"
    dest: "/etc/cron.d/hoffs-workstation-backup"
  include_role:
    name: ../../roles/common/has-cron-job

- name: "as superuser"
  block:
  - name: Start and enable service cron
    service:
      name: cronie
      state: started
      enabled: true
  become: true

# for an automated way to remove these
# sudo crontab -u hoffs -l | grep -v 'backup-workstation'  | sudo crontab -u hoffs -

# for adding
# { crontab -u user -l; echo "$this"; echo "$this_too"; } | crontab -u user -

# for deleting targeted lines
# crontab -u user -l | sed "$my_wonderful_sed_script" | crontab -u user -

# and them also clear out hoffs* from /etc/cron.d/
