---
- name:
  git:
    repo: "{{ repo_url }}"
    dest: /srv/www
    force: yes
    version: master

- name: "move static files"
  copy:
    remote_src: true
    src: "/srv/www/{{ static_files_dir }}/"
    dest: "/var/www/html"
    mode: 0755
    force: true

- name: "cleanup dir"
  file:
    path: /srv/www
    state: absent

- name: Start and enable service
  service:
    name: nginx
    state: restarted
    enabled: true
    force: true

