---
- name: Install snapraid
  apt:
    pkg:
      - "snapraid"

- name: copy snapraid config over
  copy:
    src: ./snapraid.conf
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: '0644'

- name: "clear old backup crons to make this idempotent"
  shell: "crontab -l | sed /snapraid/d | crontab -"
  args:
    executable: /bin/bash

- name: "snapraid sync and scrub every 3 hours"
  vars:
    job: "snapraid sync; snapraid scrub"
    cadence: "0 */3 * * *"
    dest: "/etc/cron.d/snapraid-sync-scrub"
    user: "root"
  include_role:
    name: "../../roles/common/has-cron-job"
