#
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    ports:
      - '8096:8096'
    volumes:
      - /mnt/app-data-disk1/app-data/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /mnt/storage/data/personal/media
        target: /media
      - type: bind
        source: /mnt/storage/data/personal/feeds
        target: /feeds
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
