---
- hosts: node-1
  vars:
    hostname: "{{device_name}}.media-center"
    ansible_host_key_checking: false
    infra_dir: "/"
  roles:
    # that it will be able to continuosly pull down
    # that it will cron
    - ../../roles/common/hostname
    - ../../roles/common/samba-client
    - ../../roles/common/base-apt
    - ../../roles/common/infra
    # - ../../roles/nas/syncthing
    # - ../../roles/nas/restic

  handlers:
    - name: snapraid sync
      command:
        argv:
          - snapraid
          - sync

    - name: snapraid scrub
      command:
        argv:
          - snapraid
          - scrub
      ignore_errors: yes

    - name: reboot
      reboot:
        reboot_timeout: 36000
