---
- hosts: node-1
  vars:
    hostname: "{{device_name}}.media-center"
    ansible_host_key_checking: false
  roles:
    # that it will be able to continuosly pull down
    # that it will cron
    # - ../../roles/hostname
    # - ../../roles/nas/proxmox-config
    # - ../../roles/base-apt
    # - ../../roles/nas/mergerfs-storage
    # - ../../roles/nas/snapraid
    # - ../../roles/nas/data-disks
    # - ../../roles/nas/parity-disks
    # - ../../roles/nas/samba-server
    # - ../../roles/nas/syncthing
    # - ../../roles/nas/restic

  handlers:
    - name: snapraid sync
      command:
        argv:
          - snapraid
          - sync

    - name: snapraid scrub
      command:
        argv:
          - snapraid
          - scrub
      ignore_errors: yes

    - name: reboot
      reboot:
        reboot_timeout: 36000
