---
- hosts: thinkcentre-a
  vars:
    hostname: "{{device_name}}.nas"
    ansible_host_key_checking: false
  roles:
    - ../../roles/hostname
    - ../../roles/base-apt
    - ../../roles/nas/mergerfs-storage
    - ../../roles/nas/snapraid
    - ../../roles/nas/data-disks
    - ../../roles/nas/parity-disks
    - ../../roles/nas/samba-server
    # - ../../roles/nas/syncthing
    # - ../../roles/nas/restic

    # Remove nag
    # echo "DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/data.status/{s/\!//;s/Active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };" > /etc/apt/apt.conf.d/no-nag-script
    # apt --reinstall install proxmox-widget-toolkit

  handlers:
    - name: snapraid sync
      command:
        argv:
          - snapraid
          - sync

    - name: snapraid scrub
      command:
        argv:
          - snapraid
          - scrub
      ignore_errors: yes

    - name: reboot
      reboot:
        reboot_timeout: 36000
