---
- hosts: rpi3-a
  vars:
    ansible_host_key_checking: false
    hostname: "{{device_name}}.pihole"
  roles:
    - ../../roles/common/hostname
    - ../../roles/manjaro/base-devel
    - ../../roles/manjaro/yay
    - ../../roles/pi-hole
