---
- hosts: rpi3-a
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
    ansible_host_key_checking: false
    hostname: "{{device_name}}.pihole"
  roles:
    - ../../roles/hostname
    - ../../roles/base-devel
    - ../../roles/yay
    - ../../roles/pi-hole
