---
- name: Install docker
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
