---
- name: "clear old backup crons to make this idempotent"
  shell: "crontab -l | sed /backup-workstation/d | crontab -"
  args:
    executable: /bin/bash

- name: "backup repos"
  vars:
    job: "sudo /infra/assets/workstation/dotfiles/bin/backup.dir git-server git /home/git daily 3"
    cadence: "@daily"
    dest: "/etc/cron.d/git-server-backup-daily"
  include_role:
    name: "../../roles/common/has-cron-job"

- name: "backup repos"
  vars:
    job: "sudo /infra/assets/workstation/dotfiles/bin/backup.dir git-server git /home/git weekly 3"
    cadence: "@weekly"
    dest: "/etc/cron.d/git-server-backup-weekly"
  include_role:
    name: "../../roles/common/has-cron-job"
