---
- name: nginx install
  import_playbook: ../nginx/deploy.yml

    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: start nginx
      service:
          name: nginx
          state: started

- hosts: all
  vars:
    packages:
      - git
  tasks:
    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: copy nginx.conf over
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/sites-enabled/mhkr.io.conf
        owner: root
        group: root
        mode: '0700'
        force: no

- name: certbot
  import_playbook: ../certbot-nginx/deploy.yml

- name: git setup
  import_playbook: ../git-server/deploy.yml
