---
- name: Add git user
  user:
    name: git

- name: Get ssh key
  shell: ssh-add -L | head -n 1
  delegate_to: 127.0.0.1
  register: ssh_key_output
  ignore_errors: true

- name: Add authorized keys for git user
  authorized_key:
    user: git
    key: "{{ ssh_key_output.stdout }}"
  when: ssh_key_output.stdout != ""
