#!/usr/bin/env sh

while read file
do
  case "$1" in
    "w")
      cp $file "$HOME/.wall.jpg" &&
      xwallpaper --focus "$HOME/.wall.jpg" &&
      notify-send "$file is now wallpaper" & ;;
    "c")
      [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
      [ -z "$destdir" ] && exit
      cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
      ;;
          "m")
      [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
      [ -z "$destdir" ] && exit
      mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
      ;;
    "y")
      echo -n "$file" | xclip -selection clipboard &&
      notify-send "$file copied to clipboard" & ;;
    "Y")
      readlink -f "$file" | xclip -selection clipboard &&
        notify-send "$(readlink -f "$file") copied to clipboard" & ;;
    "d")
      [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
  esac
done
