---
- name: "as super user"
  block:
    - name: Add authorized keys for main user
      authorized_key: user=root
                      key="{{ lookup('env', 'SSH_PUB') }}"

    - name: Allow Root
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present

    - name: Allow PAM
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^UsePAM"
                  line="UsePAM yes"
                  state=present

    - name: Allow Pubkey
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PubkeyAuthentication yes"
                  line="PubkeyAuthentication yes"
                  state=present

    - name: Disallow Challenge Response
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^ChallengeResponseAuthentication"
                  line="ChallengeResponseAuthentication no"
                  state=present

    - name: Restart ssh
      service:
        name: sshd
        state: restarted
  become: true
