---
- name: stop and disable service resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

  - name: Create symbolic link (this is where updater will look for it)
      file:
        src: "/usr/bin/pihole"
        dest: "/usr/local/bin/pihole"
        state: link
