---
- name: "as super user"
  block:
    - name: Add deploy user
      user: name=deploy

    - name: Add authorized keys for deploy user
      authorized_key: user=deploy
                      key="{{ lookup('env', 'SSH_PUB') }}"

    - name: Add authorized keys for main user
      authorized_key: user=hoffs
                      key="{{ lookup('env', 'SSH_PUB') }}"

    - name: Add deploy user to sudoers
      lineinfile:
          dest: /etc/sudoers
          regexp: "deploy ALL"
          line: "deploy ALL=(ALL) NOPASSWD: ALL"
          state: present

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present

    - name: Allow PAM
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^UsePAM"
                  line="UsePAM yes"
                  state=present

    - name: Disallow Challenge Response
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^ChallengeResponseAuthentication"
                  line="ChallengeResponseAuthentication no"
                  state=present

    - name: Restart ssh
      service:
        name: sshd
        state: restarted
  become: true
