version: '3'
services:
  syncthing:
    hostname: 'node-1-syncthing'
    image: syncthing/syncthing
    # build:
      # context: .
      # dockerfile: ../syncthing.Dockerfile
    environment:
          - PUID=1000
          - PGID=1000
    container_name: syncthing
    # command: bundle exec bin/rails s --binding 0.0.0.0
    # env_file:
    #   - ./.some_env/.env
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - /mnt/storage:/mnt/storage
      - /var/syncthing
    restart: unless-stopped
    tty: true
    stdin_open: true

  # other:
  #   image: postgis/postgis:11-2.5
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   networks:
  #     - default

networks:
  default:
